max_width = 100
reorder_imports = true
imports_layout = "Vertical"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

# nightly only

# unstable_features = true
# format_strings = false
# comment_width = 100
# wrap_comments = true
