[global]
log_level = 'debug'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = false

[mode.connections]
enabled = true

[mode.channels]
enabled = true

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = true

[telemetry]
enabled = true
host = '127.0.0.1'
port = 3001

[[chains]]
id = 'penumbra-testnet-tethys'
type = 'penumbra'
rpc_addr = 'https://rpc.testnet.penumbra.zone'
grpc_addr = 'https://grpc.testnet.penumbra.zone'
event_source = { mode = 'pull', interval = '1s' }
rpc_timeout = '15s'
account_prefix = 'fake' # not used
key_name = 'penumbra-wallet'
store_prefix = '' # not used, the commitment prefix for penumbra IBC is PenumbraAppHash
gas_price = { price = 1, denom = 'upenumbra' } # not used
max_gas = 10000000 # not used
clock_drift = '5s'
trusting_period = '2h' # this should be changed in the future
trust_threshold = { numerator = '1', denominator = '3' }


[[chains]]
id = 'penumbra-testnet-tethys-2b1d1631'
type = 'penumbra'
rpc_addr = 'https://rpc.testnet-preview.penumbra.zone'
grpc_addr = 'https://grpc.testnet-preview.penumbra.zone'
event_source = { mode = 'pull', interval = '1s' }
rpc_timeout = '15s'
account_prefix = 'fake' # not used
key_name = 'penumbra-wallet'
store_prefix = '' # not used, the commitment prefix for penumbra IBC is PenumbraAppHash
gas_price = { price = 1, denom = 'upenumbra' } # not used
max_gas = 10000000 # not used
clock_drift = '5s'
trusting_period = '2h' # this should be changed in the future
trust_threshold = { numerator = '1', denominator = '3' }
