[global]
log_level = 'debug'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = false

[mode.connections]
enabled = true

[mode.channels]
enabled = true

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = true

[telemetry]
enabled = true
host = '127.0.0.1'
port = 3001

[[chains]]
id = 'penumbra-testnet-dione'
type = 'penumbra'
rpc_addr = 'https://rpc.testnet.penumbra.zone'
grpc_addr = 'https://grpc.testnet.penumbra.zone'
event_source = { mode = 'pull', interval = '1s' }
rpc_timeout = '15s'
account_prefix = 'fake' # not used
key_name = 'penumbra-wallet'
store_prefix = '' # not used, the commitment prefix for penumbra IBC is PenumbraAppHash
gas_price = { price = 1, denom = 'upenumbra' } # not used
max_gas = 10000000 # not used
clock_drift = '5s'
trusting_period = '2h' # this should be changed in the future
trust_threshold = { numerator = '1', denominator = '3' }


[[chains]]
id = 'osmo-test-5'
type = 'cosmos-sdk'
rpc_addr = 'https://rpc.testnet.osmosis.zone'
grpc_addr = 'https://grpc.testnet.osmosis.zone'
event_source = { mode = 'pull', interval = '1s' }
rpc_timeout = '15s'
account_prefix = 'osmo' # not used
key_name = 'osmosis'
store_prefix = 'ibc' # not used, the commitment prefix for penumbra IBC is PenumbraAppHash
gas_price = { price = 0.0026, denom = 'uosmo' }
gas_multiplier = 1.1
clock_drift = '20s'
max_block_time = '10s'
trusting_period = '1days'
memo_prefix = 'Hello from Penumbra 😎🌘'
trust_threshold = { numerator = '1', denominator = '3' }
