[global]
log_level = 'debug'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = false

[mode.connections]
enabled = true

[mode.channels]
enabled = true

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = true

[telemetry]
enabled = true
host = '127.0.0.1'
port = 3001

[[chains]]
id = 'penumbra-testnet-deimos-2-e4a665af'
type = 'Penumbra'
stub_key_name = 'fake'
rpc_addr = 'https://rpc.testnet-preview.penumbra.zone'
grpc_addr = 'https://grpc.testnet-preview.penumbra.zone'
event_source = { mode = 'pull', interval = '1s' }
rpc_timeout = '15s'
clock_drift = '5s'
client_refresh_rate = '1/3'
trust_threshold = { numerator = '1', denominator = '3' }
kms_config = { spend_key = "penumbraspendkey1yf6jdguqwjc8nthqf64lq9hkfnn2wny9ssx29agnu7kufxt78ytqt4ugn6" }


[[chains]]
id = 'mocha-4'
type = 'CosmosSdk'
compat_mode = '0.34'
rpc_addr = 'https://rpc.celestia-mocha.com'
grpc_addr = 'https://grpc.celestia-mocha.com'
event_source = { mode = 'pull', interval = '1s' }
rpc_timeout = '15s'
account_prefix = 'celestia'                                  # not used
key_name = 'celestia'
store_prefix = 'ibc'                                     
gas_price = { price = 0.12, denom = 'utia' }
gas_multiplier = 1.1
clock_drift = '20s'
max_block_time = '10s'
client_refresh_rate = '1/3'
memo_prefix = 'Hello from Penumbra 😎🌘'
trust_threshold = { numerator = '1', denominator = '3' }
