name: API Docs

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/cargo-doc.yml
      - Cargo.toml
      - Cargo.lock
      - crates/**
  pull_request:
    paths:
      - .github/workflows/cargo-doc.yml
      - Cargo.toml
      - Cargo.lock
      - crates/**

env:
  RUSTFLAGS: --cfg tokio_unstable

# Cancel previous runs of this workflow when a new commit is added to the PR, branch or tag
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  cargo-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install rust toolchain
        # The script for rustdoc build requires nightly toolchain.
        uses: dtolnay/rust-toolchain@nightly
      # Loading cache takes ~15s, but saves us minutes of build.
      - name: Load rust cache
        uses: astriaorg/buildjet-rust-cache@v2.5.1
      - name: Build API documentation
        uses: actions-rs/cargo@v1
        env:
          RUSTDOCFLAGS: "--enable-index-page -Zunstable-options --cfg docsrs"
        with:
          command: doc
          args: --all-features --no-deps
      # Disabled on penumbra hermes fork
      # - name: Push API documentation to GitHub Pages
      #   if: github.ref == 'refs/heads/main'
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     deploy_key: ${{ secrets.IBC_RS_DOC_PRIVATE_KEY }}
      #     external_repository: informalsystems/hermes-api-doc
      #     publish_dir: ./target/doc
